# Arquivo: .github/workflows/reusable-checkov-scan-prd-runner.yml
# Workflow CENTRAL REUTILIZÁVEL (quando o runner está em PRD) - Indentação Corrigida

name: Reusable Checkov Scan (AWS CodeBuild in PRD)

on:
  workflow_call:
    inputs:
      terraform_directory:
        description: 'Diretório onde o código Terraform está'
        required: false
        type: string
        default: './terraform'

permissions:
  contents: read

jobs:
  checkov-scan:
    name: Run Checkov Security Scan
    # Usa o CodeBuild Runner (que está em PRD)
    runs-on: codebuild-Template-Checkov-${{ github.run_id }}-${{ github.run_attempt }} # Nome correto do runner

    steps:
      - name: Checkout Calling Repository Code
        uses: actions/checkout@v4

      - name: Install Dependencies (Checkov)
        run: |
          pip install checkov
          
      # --- PASSO Assume Role REMOVIDO ---
      
      - name: Download Central Checkov Config from S3 (PRD)
        run: |
          CONFIG_DIR="./checkov_config_central"
          # Nome correto do arquivo baseado na screenshot S3
          CONFIG_FILE=".checkov.yml" 
          BUCKET_NAME="clouddog-checkov-prd-bucket" # Nome correto do bucket
          S3_PATH="checkov"

          echo "Downloading central config $CONFIG_FILE from S3 bucket $BUCKET_NAME/$S3_PATH/ ..."
          mkdir -p $CONFIG_DIR
          # Baixa o nome de arquivo correto
          aws s3 cp "s3://$BUCKET_NAME/$S3_PATH/$CONFIG_FILE" "$CONFIG_DIR/$CONFIG_FILE"
          echo "Central config downloaded."
          ls -la $CONFIG_DIR

      - name: Run Checkov Security Scan
        run: |
          # Usa a variável com o nome de arquivo correto
          CONFIG_FILE_PATH="${{ github.workspace }}/checkov_config_central/.checkov.yml" 
          TERRAFORM_DIR="${{ inputs.terraform_directory }}"
          
          echo "Running Checkov scan on '$TERRAFORM_DIR' using central config '$CONFIG_FILE_PATH'..."
          
          if [ ! -d "$TERRAFORM_DIR" ]; then
            echo "Error: Terraform directory '$TERRAFORM_DIR' not found!"
            exit 1
          fi
          # Verificação usa a variável com o nome de arquivo correto
          if [ ! -f "$CONFIG_FILE_PATH" ]; then 
             echo "Error: Central config file '$CONFIG_FILE_PATH' not found!"
             exit 1
          fi

          # Comando usa a variável com o nome de arquivo correto
          checkov -d "$TERRAFORM_DIR" --config-file "$CONFIG_FILE_PATH"