# Workflow CENTRAL REUTILIZÁVEL (quando o runner está em PRD)

name: Reusable Checkov Scan (AWS CodeBuild in PRD)

on:
  workflow_call:
    inputs:
      terraform_directory:
        description: 'Diretório onde o código Terraform está'
        required: false
        type: string
        default: './terraform'

permissions:
  contents: read

jobs:
  checkov-scan:
    name: Run Checkov Security Scan
    # Usa o CodeBuild Runner (que está em PRD)
    runs-on: codebuild-Template-Checkov-${{ github.run_id }}-${{ github.run_attempt }} # Exemplo de nome ajustado

    steps:
      - name: Checkout Calling Repository Code
        uses: actions/checkout@v4

      - name: Install Dependencies (Checkov) # JQ não é mais necessário para o S3
        run: |
          pip install checkov
          # Opcional: Instalar YQ se for usar a estratégia de skips locais
          # yum install -y yq 
          
      # --- PASSO Assume Role REMOVIDO ---
      
     - name: Download Central Checkov Config from S3 (PRD)
        run: |
          CONFIG_DIR="./checkov_config_central"
          CONFIG_FILE=".checkov.yml" # CONFIRMADO PELA IMAGEM
          BUCKET_NAME="clouddog-checkov-prd-bucket" # CONFIRMADO PELA IMAGEM
          S3_PATH="checkov" # CONFIRMADO PELA IMAGEM

          echo "Downloading central config $CONFIG_FILE from S3 bucket $BUCKET_NAME/$S3_PATH/ ..."
          mkdir -p $CONFIG_DIR
          # Comando para baixar o arquivo .checkov.yml
          aws s3 cp "s3://$BUCKET_NAME/$S3_PATH/$CONFIG_FILE" "$CONFIG_DIR/$CONFIG_FILE"
          
          echo "Central config downloaded."
          echo "Verifying download:"
          ls -la $CONFIG_DIR # Verifica se o arquivo foi baixado

      # --- Lógica Opcional para Skips Locais (se mantida) ---
      # - name: Preparar Skips Locais 
      #   id: local_skips
      #   run: |
      #     # ... (código com yq como antes) ...

      - name: Run Checkov Security Scan
        run: |
          CONFIG_FILE_PATH="${{ github.workspace }}/checkov_config_central/.checkov.yml" # Caminho correto
          TERRAFORM_DIR="${{ inputs.terraform_directory }}"
          
          echo "Running Checkov scan on '$TERRAFORM_DIR' using central config '$CONFIG_FILE_PATH'..."
          # ... (verificações de existência de pasta/arquivo como antes) ...

          # SKIP_FLAG="" # Remover/Comentar se não usar skips locais
          # if [[ -n "${{ steps.local_skips.outputs.skip_list }}" ]]; then
          #   SKIP_FLAG="--skip-check ${{ steps.local_skips.outputs.skip_list }}"
          # fi

          # Comando final: Usa apenas o config file central do S3
          checkov -d "$TERRAFORM_DIR" --config-file "$CONFIG_FILE_PATH"
